"""Docs: https://professorwug.github.io/kmacsolves/03-zotero-cli.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03-zotero-cli.ipynb.

# %% auto #0
__all__ = ['SOLVEIT_META', 'CACHE', 'NotebookBuilder', 'nb_filename', 'zot_ls', 'zot_nb', 'paper_nb']

# %% ../nbs/03-zotero-cli.ipynb #c002
# A terminal front end: browse a Zotero library and turn its papers into SolveIt notebooks.
import json, re, asyncio, os
from pathlib import Path
from fastcore.script import call_parse

from .paper2solveit import (list_zotero, zotero_download, solve_markdown_paper,
    pdf2md, download_to_temp, _zotero_client, _describe, _authors, _year, _label)

# %% ../nbs/03-zotero-cli.ipynb #c004
# SolveIt's own notebook-level settings, copied from a dialog it wrote itself.
SOLVEIT_META = {'solveit': {'default_code': True, 'mode': 'learning',
                            'use_thinking': True, 'use_tools': True, 'ver': 2}}

class NotebookBuilder:
    """Collects `solve_markdown_paper` blocks into a notebook file instead of a live dialog.

    Its `add` method stands in for `dialoghelper.add_msg`, so the same splitting and citation
    logic that runs inside SolveIt produces the file you get from the terminal.
    """
    def __init__(self, header=()):
        self.cells = [self._cell(h, 'code') for h in header]
    def _cell(self, content, kind='markdown', collapsed=False):
        self._n = getattr(self, '_n', 0) + 1
        cell = {'cell_type': kind, 'id': f'p2s{self._n:04d}',
                'metadata': {'hide_input': True} if collapsed else {},
                'source': content.splitlines(keepends=True)}
        if kind == 'code': cell |= {'execution_count': None, 'outputs': []}
        return cell
    async def add(self, content, placement='at_end', id=None, i_collapsed=None):
        "Stand-in for `add_msg`: append a block, or slot one in after an earlier block."
        cell = self._cell(content, collapsed=bool(i_collapsed))
        if placement == 'add_after':
            at = next(i for i, c in enumerate(self.cells) if c['id'] == id)
            self.cells.insert(at + 1, cell)
        else: self.cells.append(cell)
        return cell['id']
    def write(self, path):
        "Save as a notebook SolveIt will open in learning mode."
        nb = {'cells': self.cells, 'metadata': SOLVEIT_META, 'nbformat': 4, 'nbformat_minor': 5}
        Path(path).write_text(json.dumps(nb, indent=1, ensure_ascii=False) + '\n')
        return Path(path)

# %% ../nbs/03-zotero-cli.ipynb #c006
def nb_filename(data, path='.'):
    "A filename in the reading-nbs style: 'Vaswani17 - Attention Is All You Need.ipynb'."
    who = re.sub(r'\s*(et al\.|&.*)$', '', _authors(data)).strip()
    title = data.get('title') or data.get('filename') or 'Paper'
    stem = f"{who}{_year(data)[2:]} - {title}" if who else title
    stem = re.sub(r'[\\/:*?"<>|]', '-', stem).strip()[:120]
    return Path(path) / f"{stem}.ipynb"

# %% ../nbs/03-zotero-cli.ipynb #c008
CACHE = Path(os.environ.get('XDG_CACHE_HOME', Path.home() / '.cache')) / 'kmacsolves' / 'listing.json'

def _save_listing(listing, local):
    "Remember what `zot_ls` just showed, so `zot_nb` in a later process can resolve its numbers."
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    CACHE.write_text(json.dumps({
        'kind': listing.kind, 'title': listing.title, 'local': local,
        'entries': [{'key': e['key'], 'label': _label(e), 'data': e['data'],
                     'pdf': listing.pdfs.get(e['key'])} for e in listing.entries]}))

def _load_listing():
    "The listing `zot_ls` last wrote, or a clear error if there isn't one."
    if not CACHE.exists(): raise SystemExit(
        "Nothing listed yet — run `zot-ls <collection>` first, or pass a Zotero item key.")
    return json.loads(CACHE.read_text())

def _cached_entry(n):
    "Entry `n` from the saved listing, checking it's a paper rather than a collection."
    d = _load_listing()
    if d['kind'] != 'item': raise SystemExit(
        f"The last listing was of collections. Run `zot-ls <collection>` to list papers first.")
    if not 1 <= n <= len(d['entries']): raise SystemExit(
        f"{n} is outside the last listing of {len(d['entries'])} items ({d['title']}).")
    return d['entries'][n-1], d

# %% ../nbs/03-zotero-cli.ipynb #c010
@call_parse(pos=['collection'])
def zot_ls(
    collection: str = None,   # Collection name, or its number from a previous listing
    web: bool = False,        # Read via the Zotero web API instead of the desktop app
):
    "List Zotero collections, or the papers in one, numbered for `zot-nb`."
    kw = {'local': not web}
    listing = list_zotero(int(collection) if (collection or '').isdigit() else collection, **kw)
    _save_listing(listing, kw['local'])
    print(repr(listing))
    if listing.kind == 'collection': print("\nList one with `zot-ls <name-or-number>`.")
    else: print(f"\nConvert one with `zot-nb <number>`.  ({len(listing.pdfs)} of "
                f"{len(listing)} have a PDF)")

# %% ../nbs/03-zotero-cli.ipynb #c012
def _md_title(md):
    "A paper's own title, taken from the first heading of the converted markdown."
    m = re.search(r'^#+\s*(.+)', md, re.M)
    return m.group(1).strip() if m else None

async def _build(pdf, data, out, path, **kwargs):
    "Shared tail of the two converters: OCR to markdown, then lay it out as a notebook."
    # Extracted figures are referenced as 'figures/x.jpg', relative to the notebook — so they
    # have to be written beside it rather than into whatever directory you happened to run from.
    dest = Path(out).parent if out else Path(path)
    dest.mkdir(parents=True, exist_ok=True)
    o = await pdf2md(str(pdf), path=dest)
    # A URL carries no metadata, so fall back to whatever the paper calls itself.
    if not data.get('title'): data = data | {'title': _md_title(o["markdown"]) or 'Paper'}
    b = NotebookBuilder(header=['from kmacsolves.paper2solveit import *',
                                f'# {_describe(data)}'])
    await solve_markdown_paper(o["markdown"], add=b.add, **kwargs)
    return b.write(out or nb_filename(data, path))

@call_parse
def zot_nb(
    item: str,                # Number from `zot-ls`, or a Zotero item key
    out: str = None,          # Write here instead of an auto-named file
    path: str = '.',          # Directory for the auto-named file
    web: bool = False,        # Read via the Zotero web API instead of the desktop app
):
    "Turn a paper in your Zotero library into a SolveIt notebook."
    if item.isdigit():
        entry, listing = _cached_entry(int(item))
        if not entry['pdf']: raise SystemExit(
            f"{entry['label']} has no PDF attached — `zot-ls` marks these '(no PDF)'.")
        # The listing already worked out which attachment to fetch, so go straight to it.
        key, data, local = entry['pdf'], entry['data'], listing['local']
    else:
        local = not web
        data = _zotero_client(local=local).item(item)['data']
        key = item
    print(f"Converting {_describe(data)} …")
    pdf = zotero_download(key, local=local)
    print(f"Wrote {asyncio.run(_build(pdf, data, out, path))}")

# %% ../nbs/03-zotero-cli.ipynb #c017
@call_parse
def paper_nb(
    url: str,                 # arXiv abstract URL, or a direct link to a PDF
    out: str = None,          # Write here instead of an auto-named file
    path: str = '.',          # Directory for the auto-named file
):
    "Turn a paper at a public URL into a SolveIt notebook."
    f = download_to_temp(url)
    print(f"Wrote {asyncio.run(_build(f, {}, out, path))}")
