"""Docs: https://professorwug.github.io/kmacsolves/02-paper2solveit.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02-paper2solveit.ipynb.

# %% auto #0
__all__ = ['dlab_params', 'dlab_url', 'submit_marker', 'submit_markers', 'poll_marker', 'poll_markers', 'convert_pdf',
           'convert_pdfs', 'pdf2md', 'pdfs2md', 'download_to_temp', 'split_markdown_into_cells', 'extract_references',
           'numbered_references', 'cited_numbers', 'solve_markdown_paper', 'paper2solveit', 'ZoteroListing',
           'list_zotero', 'zotero_download', 'zotero_pdf']

# %% ../nbs/02-paper2solveit.ipynb #d5d73954
from dialoghelper import *
from IPython.display import Markdown


# %% ../nbs/02-paper2solveit.ipynb #26c3e6ec
# Jeremy Howard's pythonic wrapper around the Datalab Marker OCR API, from https://gist.github.com/jph00/f3bcfa015660b031d0b92c2391d21921 - captured inline for ease of reproducibility
from fastcore.utils import *
from IPython.display import Markdown
from httpx import get as xget,post as xpost
import time, asyncio, httpx
from base64 import b64decode
from fastcore.meta import use_kwargs_dict,delegates
dlab_params = dict(output_format='markdown', force_ocr=False, format_lines=False, paginate=False, use_llm=False,
    strip_existing_ocr=False, disable_image_extraction=False, max_pages=None, page_range=None)
dlab_url="https://www.datalab.to/api/v1/marker"

@use_kwargs_dict(**dlab_params)
async def submit_marker(fname=None, file=None, file_url=None, key=None, url=dlab_url, **kwargs):
    "Submit PDF to Datalab Marker API for conversion"
    key = key or os.environ.get("DATALAB_KEY")
    if fname: file = open(fname, "rb")
    try:
        files = {'file': (file.name, file, 'application/pdf')} if file else None
        if file_url: kwargs['file_url'] = file_url
        async with httpx.AsyncClient() as c:
            res = await c.post(url, files=files, data=kwargs, headers={"X-Api-Key": key})
            return res.json()
    finally:
        if fname and file: file.close()
@delegates(submit_marker)
async def submit_markers(files=None, fnames=None, file_urls=None, **kwargs):
    "Submit multiple PDFs concurrently, return list of response dicts"
    tasks = [submit_marker(file=f, **kwargs) for f in L(files)
        ] + [submit_marker(file_url=u, **kwargs) for u in L(file_urls)
        ] + [submit_marker(fname=u, **kwargs) for u in L(fnames)]
    return await asyncio.gather(*tasks)
async def poll_marker(d, key=None, max_polls=300, delay=2, verbose=False):
    "Poll Marker API until conversion complete"
    if not d.get('success', True): raise ValueError(f"Submit failed: {d.get('error')}")
    check_url = d['request_check_url']
    key = key or os.environ.get("DATALAB_KEY")
    async with httpx.AsyncClient() as c:
        for _ in range(max_polls):
            res = await c.get(check_url, headers={"X-Api-Key": key})
            data = res.json()
            if verbose: print(data["status"], end='; ')
            if data["status"] == "complete": return data
            if data["status"] == "failed": raise RuntimeError(f"Conversion failed: {data.get('error')}")
            await asyncio.sleep(delay)
    raise TimeoutError(f"Polling timed out after {max_polls * delay}s")
async def poll_markers(ds, key=None, max_polls=300, delay=2, verbose=False):
    "Poll multiple Marker API requests concurrently"
    return await asyncio.gather(*[poll_marker(d, key, max_polls, delay, verbose) for d in ds])
@delegates(submit_marker)
async def convert_pdf(fname=None, file=None, file_url=None, key=None, max_polls=300, delay=2, verbose=False, **kwargs):
    "Submit and poll until complete, return result"
    r = await submit_marker(fname=fname, file=file, file_url=file_url, key=key, **kwargs)
    return await poll_marker(r, key=key, max_polls=max_polls, delay=delay, verbose=verbose)
@delegates(submit_markers)
async def convert_pdfs(files=None, fnames=None, file_urls=None, key=None, max_polls=300, delay=2, verbose=False, **kwargs):
    "Submit multiple PDFs and poll all until complete"
    rs = await submit_markers(files=files, fnames=fnames, file_urls=file_urls, key=key, **kwargs)
    return await poll_markers(rs, key=key, max_polls=max_polls, delay=delay, verbose=verbose)
def _save_md(r, stem, path):
    path = Path(path)
    figures = path / "figures"
    figures.mkdir(exist_ok=True, parents=True)

    markdown = r["markdown"]
    for name, data in r["images"].items():
        (figures / name).write_bytes(b64decode(data))
        markdown = markdown.replace(f"]({name})", f"](figures/{name})")

    r["markdown"] = markdown
    (path / f"{stem}.md").write_text(markdown)

@delegates(convert_pdf)
async def pdf2md(fname, path='.', **kwargs):
    "Convert PDF to markdown and save with images"
    path = Path(path)
    path.mkdir(exist_ok=True, parents=True)
    r = await convert_pdf(fname=fname, **kwargs)
    _save_md(r, Path(fname).stem, path)
    return r

@delegates(convert_pdfs)
async def pdfs2md(fnames, path='.', **kwargs):
    "Convert multiple PDFs to markdown and save with images"
    path = Path(path)
    path.mkdir(exist_ok=True, parents=True)
    rs = await convert_pdfs(fnames=fnames, **kwargs)
    for fname,r in zip(fnames, rs): _save_md(r, Path(fname).stem, path)
    return rs

# %% ../nbs/02-paper2solveit.ipynb #7f4b6ca1
import httpx
from pathlib import Path
from tempfile import NamedTemporaryFile
def download_to_temp(url):
    if 'arxiv.org/abs/' in url: url = url.replace('/abs/', '/pdf/') + '.pdf'
    tmp = NamedTemporaryFile(delete=False, suffix=Path(url).suffix)
    content = httpx.get(url, follow_redirects=True).content
    tmp.write(content)
    tmp.flush()
    tmp.close()
    return Path(tmp.name)


# %% ../nbs/02-paper2solveit.ipynb #26c4b421
def split_markdown_into_cells(markdown_text):
    """Split markdown into cells: preamble, then headers + paragraphs"""
    lines = markdown_text.split('\n')
    first_header_idx = None
    for i, line in enumerate(lines):
        if line.startswith('##'):
            first_header_idx = i
            break
    cells = []
    # Everything before first header = one cell (all of the authors and affiliations)
    if first_header_idx:
        preamble = '\n'.join(lines[:first_header_idx]).strip()
        if preamble:
            cells.append(preamble)
    # For rest, separate headers into their own cells; for everything else, split by double \n\n via two passes
    current_section = []
    for line in lines[first_header_idx:] if first_header_idx else lines:
        if line.startswith('#'):
            if current_section:
                cells.append('\n'.join(current_section).strip())
                current_section = []
            cells.append(line[1:] if line.startswith('##') else line)
        else:
            current_section.append(line)
    if current_section:
        content = '\n'.join(current_section).strip()
        if content:
            cells.append(content)
    # Split non-header cells by paragraphs
    final_cells = []
    for cell in cells:
        if cell.startswith('#'):
            final_cells.append(cell)
        else:
            paragraphs = cell.split('\n\n')
            final_cells.extend([p.strip() for p in paragraphs if p.strip()])
    
    return final_cells

# %% ../nbs/02-paper2solveit.ipynb #e0d2f51c
import re

def extract_references(markdown_text):
    """The bibliography: everything under a References/Bibliography heading.

    Stops at the next heading of the same level or higher, so subsections of the
    bibliography stay with it. Matching any depth matters — papers head their references
    with `##` and books with `#`.
    """
    m = re.search(r'^(#+)[ \t]*(?:References|Bibliography)[ \t]*$', markdown_text, re.M | re.I)
    if not m: return ""
    rest = markdown_text[m.end():]
    nxt = re.search(rf'^#{{1,{len(m.group(1))}}}(?!#)', rest, re.M)
    return (rest[:nxt.start()] if nxt else rest).strip()

def numbered_references(refs_section):
    "Map citation numbers to their entries, for bibliographies that read `[12] Author, ...`."
    out = {}
    for m in re.finditer(r'^[ \t]*(?:[-*][ \t]*)?\[(\d+)\][ \t]*(.+?)(?=^[ \t]*(?:[-*][ \t]*)?\[\d+\]|\Z)',
                         refs_section, re.M | re.S):
        out[int(m.group(1))] = ' '.join(m.group(2).split())
    return out

def cited_numbers(text):
    "The citation numbers a passage refers to, expanding `[3, 5]` and `[7-9]`."
    out = set()
    for m in re.finditer(r'\[(\d+)[ \t]*[-–][ \t]*(\d+)\]|\[([\d\s,;]*\d)\]', text):
        if m.group(1): out |= set(range(int(m.group(1)), int(m.group(2)) + 1))
        else: out |= {int(n) for n in re.split(r'[,;\s]+', m.group(3)) if n}
    return out

def _is_heading(cell): return cell.startswith('#') and '\n' not in cell

def _footnote_citations(cell, all_citations, citation_patterns):
    "Swap author-year citations for numbered markers; returns the new text and what it cited."
    used = set()
    for pattern in citation_patterns:
        for match in re.finditer(pattern, cell):
            cite = match.group(0)
            if cite in all_citations:
                used.add(cite)
                cell = cell.replace(cite, f"[{all_citations[cite]}]", 1)
    return cell, used

async def solve_markdown_paper(markdown_text, citation_patterns=None, add=None):
    """Turn a markdown academic paper into appended solveit blocks for incremental reading.

    `add` is where the blocks go: `add_msg` by default, which appends to the dialog you're
    reading in. Pass something else — see `NotebookBuilder` — to build a notebook file instead.

    Papers citing as `(Author, 2020)` get their citations replaced by numbered markers.
    Papers citing as `[12]` are left as they are: the numbering is already the paper's own,
    and rewriting it would collide with the markers this function emits. Either way each
    section gets a folded cheatsheet resolving the markers that appear in it.
    """
    if add is None: add = add_msg

    if citation_patterns is None:
        citation_patterns = [
            r'\([A-Z][^)]*,\s*\d{4}[a-z]?(?:;\s*[^)]*\d{4}[a-z]?)*\)',  # (Author, 2020)
            r'\([A-Z][^)]*\s+\d{4}[a-z]?(?:;\s*[^)]*\d{4}[a-z]?)*\)'    # (Author 2020)
        ]

    refs_section = extract_references(markdown_text)
    cells = split_markdown_into_cells(markdown_text)
    entries = numbered_references(refs_section)
    numeric = len(entries) >= 3 and any(cited_numbers(c) & entries.keys() for c in cells)

    # Number the author-year citations in order of first appearance
    all_citations, counter = {}, 1
    if not numeric:
        for cell in cells:
            for pattern in citation_patterns:
                for match in re.finditer(pattern, cell):
                    if match.group(0) not in all_citations:
                        all_citations[match.group(0)] = counter
                        counter += 1

    # Add full bibliography at start (collapsed)
    if refs_section:
        await add(content=f"### Full References\n\n{refs_section}", placement='at_end', i_collapsed=1)

    # Track sections: {header_id: set_of_citations}
    section_citations = {}
    current_header_id = None
    in_refs = False

    for cell in cells:
        if _is_heading(cell):
            # The bibliography's own cells cite everything; a cheatsheet there would just
            # repeat it, so note when we're inside it and collect nothing until we leave.
            in_refs = bool(re.match(r'#+[ \t]*(?:References|Bibliography)\b', cell, re.I))
            current_header_id = await add(content=cell, placement='at_end')
            section_citations[current_header_id] = set()
        elif in_refs:
            await add(content=cell, placement='at_end')
        else:
            if numeric: text, used = cell, cited_numbers(cell) & entries.keys()
            else: text, used = _footnote_citations(cell, all_citations, citation_patterns)
            if current_header_id: section_citations[current_header_id] |= used
            await add(content=text, placement='at_end')

    # Now go back and insert cheatsheets after each header
    for header_id, used in section_citations.items():
        if not used: continue
        lines = ([f"[{n}]: {entries[n]}" for n in sorted(used)] if numeric else
                 [f"[{all_citations[c]}]: {c}" for c in sorted(used, key=lambda x: all_citations[x])])
        await add(content="### Citations in this section\n\n" + "\n".join(lines),
                  placement='add_after', id=header_id, i_collapsed=1)

# %% ../nbs/02-paper2solveit.ipynb #462caa66
async def paper2solveit(url, **kwargs):
    """Download a paper from URL (arXiv or PDF) and process into solveit blocks.
    
    Args:
        url: arXiv abstract URL or direct PDF link
        **kwargs: passed to solve_markdown_paper (e.g., citation_patterns)
    """
    # Download PDF to temp file
    f = download_to_temp(url)
    
    # Convert to markdown
    o = await pdf2md(str(f))
    
    # Process into solveit blocks with citations
    await solve_markdown_paper(o["markdown"], **kwargs)

# %% ../nbs/02-paper2solveit.ipynb #2d97de59
__all__ = [
    'pdf2md', 'pdfs2md',  # Jeremy's Marker API wrappers
    'download_to_temp',
    'split_markdown_into_cells',
    'extract_references', 'numbered_references', 'cited_numbers',
    'solve_markdown_paper',
    'paper2solveit',
    'list_zotero', 'zotero_pdf', 'zotero_download', 'ZoteroListing',  # Zotero library support
]

# %% ../nbs/02-paper2solveit.ipynb #a1f0c212
# Zotero support: pull a paper straight from your own library instead of a public URL.
import os, re, httpx
from pathlib import Path
from tempfile import NamedTemporaryFile
from urllib.parse import urlparse, unquote

def _zotero_client(library_id=None, api_key=None, library_type='user', local=False):
    "Build a pyzotero client, defaulting to the `ZOTERO_USER_ID`/`ZOTERO_API_KEY` env vars."
    try: from pyzotero.zotero import Zotero
    except ImportError:
        try: from pyzotero import Zotero
        except ImportError: raise ImportError(
            "Zotero support needs pyzotero — install it with `pip install pyzotero`.") from None
    library_id = library_id or os.environ.get('ZOTERO_USER_ID')
    # The local API serves whichever library the running Zotero has open, under the id 0,
    # so local mode needs no credentials at all.
    if local: return Zotero(library_id or '0', library_type, local=True)
    if not library_id: raise ValueError(
        "No Zotero library id: set ZOTERO_USER_ID (find yours at zotero.org/settings/keys) "
        "or pass library_id=, or use local=True to read from the Zotero app on this machine.")
    api_key = api_key or os.environ.get('ZOTERO_API_KEY')
    if not api_key: raise ValueError(
        "No Zotero API key: set ZOTERO_API_KEY (create one at zotero.org/settings/keys) "
        "or pass api_key=, or use local=True to talk to a running Zotero 7 desktop app.")
    return Zotero(library_id, library_type, api_key)

# %% ../nbs/02-paper2solveit.ipynb #a1f0c214
def _year(d):
    "First 4-digit year in an item's date field, or '' if there isn't one."
    m = re.search(r'\d{4}', d.get('date') or '')
    return m.group(0) if m else ''

def _authors(d):
    "Short author string: 'Smith', 'Smith & Jones', or 'Smith et al.'"
    cs = d.get('creators') or []
    names = [c.get('lastName') or c.get('name') or '' for c in cs if c.get('creatorType') == 'author']
    names = [n for n in (names or [c.get('lastName') or c.get('name') or '' for c in cs]) if n]
    if not names: return ''
    if len(names) == 1: return names[0]
    if len(names) == 2: return f'{names[0]} & {names[1]}'
    return f'{names[0]} et al.'

def _describe(d):
    "One-line human label for a Zotero item."
    bits = [b for b in (_authors(d), _year(d)) if b]
    title = d.get('title') or d.get('name') or d.get('filename') or '(untitled)'
    return f"{title} — {', '.join(bits)}" if bits else title

def _label(entry):
    "How an entry appears in a listing: items get authors and a year, collections a size."
    d = entry['data']
    n = (entry.get('meta') or {}).get('numItems')
    if d.get('itemType') is None and n is not None: return f"{_describe(d)} ({n})"
    return _describe(d)

# %% ../nbs/02-paper2solveit.ipynb #a1f0c216
class ZoteroListing:
    "A numbered list of Zotero collections or items; renders as markdown, indexes like a list."
    def __init__(self, title, entries, kind, pdfs=None):
        self.title, self.entries, self.kind = title, entries, kind
        self.pdfs = pdfs or {}   # item key -> key of the PDF to convert, for entries that have one
    def __len__(self): return len(self.entries)
    def __iter__(self): return iter(self.entries)
    def __getitem__(self, i):
        "1-based lookup, matching the numbers shown in the listing."
        if not 1 <= i <= len(self.entries): raise IndexError(
            f"{i} is outside the listing (1–{len(self.entries)}).")
        return self.entries[i-1]
    def _lines(self):
        out = []
        for i, e in enumerate(self.entries, 1):
            gap = '' if self.kind == 'collection' or e['key'] in self.pdfs else '  *(no PDF)*'
            out.append(f"{i}. {_label(e)}{gap}")
        return out
    def _repr_markdown_(self):
        if not self.entries: return f"**{self.title}** — nothing here."
        return '\n'.join([f"**{self.title}**", ''] + self._lines())
    def __repr__(self): return '\n'.join([self.title] + [l.replace('  *(no PDF)*', '  (no PDF)')
                                                         for l in self._lines()])

# %% ../nbs/02-paper2solveit.ipynb #a1f0c218
_last_listing = None  # what `list_zotero` showed most recently, so `zotero_pdf(n)` can resolve n

def list_zotero(collection=None, **kwargs):
    """List your Zotero collections, or the items inside one, numbered for use with `zotero_pdf`.

    Args:
        collection: a collection name (case-insensitive, partial matches allowed), or the
            number of a collection from the previous `list_zotero()` listing. Omit it to
            list the collections themselves.
        **kwargs: passed to `_zotero_client` (library_id, api_key, library_type, local)
    """
    global _last_listing
    zot = _zotero_client(**kwargs)
    # A number picks the collection outright, so drilling in works even when two share a name.
    col = (_resolve_number(collection, 'collection') if isinstance(collection, int) else
           _match_collection(zot, collection) if collection is not None else None)
    if col is None:
        cols = sorted(zot.everything(zot.collections()), key=lambda c: c['data']['name'].lower())
        _last_listing = ZoteroListing('Zotero collections', cols, 'collection')
    else:
        # `collection_items` returns the collection's items *and* their attachments, so one
        # round trip tells us both what's in here and which entries have a PDF to convert.
        entries = zot.everything(zot.collection_items(col['key']))
        items = [e for e in entries if not e['data'].get('parentItem')
                 and e['data'].get('itemType') != 'note']
        _last_listing = ZoteroListing(f"{col['data']['name']} ({len(items)} items)", items,
                                      'item', _pdf_map(entries))
    return _last_listing

def _pdf_map(entries):
    "Map each item key to the PDF to convert for it: itself if it is one, else its first PDF child."
    out = {}
    for e in entries:
        d = e['data']
        if d.get('contentType') == 'application/pdf':
            out.setdefault(d.get('parentItem') or d['key'], d['key'])
    return out

def _resolve_number(n, kind):
    "Look up entry `n` in the last listing, checking it holds the kind of thing we want."
    if _last_listing is None: raise ValueError(
        f"No listing to index into — run `list_zotero()` first.")
    if _last_listing.kind != kind: raise ValueError(
        f"The last listing was of {_last_listing.kind}s, not {kind}s. "
        f"Run `list_zotero({'' if kind == 'collection' else 'collection_name'})` first.")
    return _last_listing[n]

def _match_collection(zot, name):
    "Find a collection by name: exact (case-insensitive) first, then substring."
    cols = zot.everything(zot.collections())
    exact = [c for c in cols if c['data']['name'].lower() == name.lower()]
    if len(exact) == 1: return exact[0]
    hits = exact or [c for c in cols if name.lower() in c['data']['name'].lower()]
    if not hits: raise ValueError(
        f"No Zotero collection matching {name!r}. Run `list_zotero()` to see them all.")
    if len(hits) > 1:
        names = [c['data']['name'] for c in hits]
        detail = ("several collections share that name" if len(set(names)) == 1
                  else f"it matches {', '.join(sorted(set(names)))}")
        raise ValueError(f"{name!r} is ambiguous — {detail}. "
                         "Pick one by its number from `list_zotero()` instead.")
    return hits[0]

# %% ../nbs/02-paper2solveit.ipynb #a1f0c21a
def _pdf_key(zot, item, pdfs=None):
    "Key of the PDF to convert, from the listing's attachment map or by asking for the children."
    d = item['data']
    if pdfs and d['key'] in pdfs: return pdfs[d['key']]
    if d.get('itemType') == 'attachment':
        if d.get('contentType') == 'application/pdf': return d['key']
        raise ValueError(f"{_describe(d)!r} is a {d.get('contentType')} attachment, not a PDF.")
    for ch in zot.children(d['key']):
        cd = ch['data']
        if cd.get('itemType') == 'attachment' and cd.get('contentType') == 'application/pdf':
            return cd['key']
    raise ValueError(f"No PDF attached to {_describe(d)!r} — the listing marks these '(no PDF)'. "
                     "Add one in Zotero, or pick a different item.")

def _attachment_bytes(zot, key):
    """Read an attachment's bytes.

    The web API sends the file itself, but the local API answers with a 302 to a `file://`
    URL — Zotero expects you to open the path yourself, which is fine, since local mode means
    the library is on this machine. Asking for the file also prompts Zotero to fetch it if it's
    stored online and hasn't been downloaded yet.
    """
    if not getattr(zot, 'local', False): return zot.file(key)
    url = f"{zot.endpoint}/{zot.library_type}/{zot.library_id}/items/{key}/file"
    loc = httpx.get(url, follow_redirects=False).headers.get('location', '')
    if not loc.startswith('file://'): return zot.file(key)
    p = Path(unquote(urlparse(loc).path))
    if not p.exists(): raise FileNotFoundError(
        f"Zotero points at {p}, but nothing's there yet. Files stored online download on "
        "demand, so opening the item in Zotero once and retrying usually fixes it.")
    return p.read_bytes()

def zotero_download(item, path=None, **kwargs):
    """Download a Zotero item's PDF, returning the path it was written to.

    Args:
        item: a number from the last `list_zotero` listing, a Zotero item key, or an item dict
        path: where to write the PDF (a temp file if omitted)
        **kwargs: passed to `_zotero_client`
    """
    zot = _zotero_client(**kwargs)
    pdfs = None
    if isinstance(item, int): item, pdfs = _resolve_number(item, 'item'), _last_listing.pdfs
    if isinstance(item, str): item = zot.item(item)
    key = _pdf_key(zot, item, pdfs)
    try: content = _attachment_bytes(zot, key)
    except FileNotFoundError: raise          # already says exactly what's wrong
    except Exception as e: raise RuntimeError(
        f"Couldn't download the PDF for {_describe(item['data'])!r} ({e}). Zotero serves files "
        "only when they're stored in your library and synced — linked-file attachments, and "
        "libraries with file sync off, aren't retrievable through the API."
    ) from e
    if path is None:
        tmp = NamedTemporaryFile(delete=False, suffix='.pdf')
        tmp.write(content); tmp.close()
        return Path(tmp.name)
    path = Path(path)
    path.write_bytes(content)
    return path

# %% ../nbs/02-paper2solveit.ipynb #a1f0c21c
async def zotero_pdf(item, **kwargs):
    """Turn a PDF from your Zotero library into solveit blocks.

    Pair it with `list_zotero`: list a collection, then pass the number of the paper you want.

        list_zotero('Reading List')
        await zotero_pdf(3)

    Args:
        item: a number from the last `list_zotero` listing, a Zotero item key, or an item dict
        **kwargs: split between `_zotero_client` (library_id, api_key, library_type, local)
            and `solve_markdown_paper` (e.g. citation_patterns)
    """
    zkw = {k: kwargs.pop(k) for k in ('library_id', 'api_key', 'library_type', 'local')
           if k in kwargs}
    f = zotero_download(item, **zkw)
    o = await pdf2md(str(f))
    await solve_markdown_paper(o["markdown"], **kwargs)
