"""Docs: https://professorwug.github.io/kmacsolves/02-paper2solveit.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02-paper2solveit.ipynb.

# %% auto #0
__all__ = ['dlab_params', 'dlab_url', 'submit_marker', 'submit_markers', 'poll_marker', 'poll_markers', 'convert_pdf',
           'convert_pdfs', 'pdf2md', 'pdfs2md', 'download_to_temp', 'split_markdown_into_cells', 'solve_markdown_paper',
           'paper2solveit']

# %% ../nbs/02-paper2solveit.ipynb #d5d73954
from dialoghelper import *
from IPython.display import Markdown


# %% ../nbs/02-paper2solveit.ipynb #26c3e6ec
# Jeremy Howard's pythonic wrapper around the Datalab Marker OCR API, from https://gist.github.com/jph00/f3bcfa015660b031d0b92c2391d21921 - captured inline for ease of reproducibility
from fastcore.utils import *
from IPython.display import Markdown
from httpx import get as xget,post as xpost
import time, asyncio, httpx
from base64 import b64decode
from fastcore.meta import use_kwargs_dict,delegates
dlab_params = dict(output_format='markdown', force_ocr=False, format_lines=False, paginate=False, use_llm=False,
    strip_existing_ocr=False, disable_image_extraction=False, max_pages=None, page_range=None)
dlab_url="https://www.datalab.to/api/v1/marker"

@use_kwargs_dict(**dlab_params)
async def submit_marker(fname=None, file=None, file_url=None, key=None, url=dlab_url, **kwargs):
    "Submit PDF to Datalab Marker API for conversion"
    key = key or os.environ.get("DATALAB_KEY")
    if fname: file = open(fname, "rb")
    try:
        files = {'file': (file.name, file, 'application/pdf')} if file else None
        if file_url: kwargs['file_url'] = file_url
        async with httpx.AsyncClient() as c:
            res = await c.post(url, files=files, data=kwargs, headers={"X-Api-Key": key})
            return res.json()
    finally:
        if fname and file: file.close()
@delegates(submit_marker)
async def submit_markers(files=None, fnames=None, file_urls=None, **kwargs):
    "Submit multiple PDFs concurrently, return list of response dicts"
    tasks = [submit_marker(file=f, **kwargs) for f in L(files)
        ] + [submit_marker(file_url=u, **kwargs) for u in L(file_urls)
        ] + [submit_marker(fname=u, **kwargs) for u in L(fnames)]
    return await asyncio.gather(*tasks)
async def poll_marker(d, key=None, max_polls=300, delay=2, verbose=False):
    "Poll Marker API until conversion complete"
    if not d.get('success', True): raise ValueError(f"Submit failed: {d.get('error')}")
    check_url = d['request_check_url']
    key = key or os.environ.get("DATALAB_KEY")
    async with httpx.AsyncClient() as c:
        for _ in range(max_polls):
            res = await c.get(check_url, headers={"X-Api-Key": key})
            data = res.json()
            if verbose: print(data["status"], end='; ')
            if data["status"] == "complete": return data
            if data["status"] == "failed": raise RuntimeError(f"Conversion failed: {data.get('error')}")
            await asyncio.sleep(delay)
    raise TimeoutError(f"Polling timed out after {max_polls * delay}s")
async def poll_markers(ds, key=None, max_polls=300, delay=2, verbose=False):
    "Poll multiple Marker API requests concurrently"
    return await asyncio.gather(*[poll_marker(d, key, max_polls, delay, verbose) for d in ds])
@delegates(submit_marker)
async def convert_pdf(fname=None, file=None, file_url=None, key=None, max_polls=300, delay=2, verbose=False, **kwargs):
    "Submit and poll until complete, return result"
    r = await submit_marker(fname=fname, file=file, file_url=file_url, key=key, **kwargs)
    return await poll_marker(r, key=key, max_polls=max_polls, delay=delay, verbose=verbose)
@delegates(submit_markers)
async def convert_pdfs(files=None, fnames=None, file_urls=None, key=None, max_polls=300, delay=2, verbose=False, **kwargs):
    "Submit multiple PDFs and poll all until complete"
    rs = await submit_markers(files=files, fnames=fnames, file_urls=file_urls, key=key, **kwargs)
    return await poll_markers(rs, key=key, max_polls=max_polls, delay=delay, verbose=verbose)
def _save_md(r, stem, path):
    path = Path(path)
    figures = path / "figures"
    figures.mkdir(exist_ok=True, parents=True)

    markdown = r["markdown"]
    for name, data in r["images"].items():
        (figures / name).write_bytes(b64decode(data))
        markdown = markdown.replace(f"]({name})", f"](figures/{name})")

    r["markdown"] = markdown
    (path / f"{stem}.md").write_text(markdown)

@delegates(convert_pdf)
async def pdf2md(fname, path='.', **kwargs):
    "Convert PDF to markdown and save with images"
    path = Path(path)
    path.mkdir(exist_ok=True, parents=True)
    r = await convert_pdf(fname=fname, **kwargs)
    _save_md(r, Path(fname).stem, path)
    return r

@delegates(convert_pdfs)
async def pdfs2md(fnames, path='.', **kwargs):
    "Convert multiple PDFs to markdown and save with images"
    path = Path(path)
    path.mkdir(exist_ok=True, parents=True)
    rs = await convert_pdfs(fnames=fnames, **kwargs)
    for fname,r in zip(fnames, rs): _save_md(r, Path(fname).stem, path)
    return rs

# %% ../nbs/02-paper2solveit.ipynb #7f4b6ca1
import httpx
from pathlib import Path
from tempfile import NamedTemporaryFile
def download_to_temp(url):
    if 'arxiv.org/abs/' in url: url = url.replace('/abs/', '/pdf/') + '.pdf'
    tmp = NamedTemporaryFile(delete=False, suffix=Path(url).suffix)
    content = httpx.get(url, follow_redirects=True).content
    tmp.write(content)
    tmp.flush()
    tmp.close()
    return Path(tmp.name)


# %% ../nbs/02-paper2solveit.ipynb #26c4b421
def split_markdown_into_cells(markdown_text):
    """Split markdown into cells: preamble, then headers + paragraphs"""
    lines = markdown_text.split('\n')
    first_header_idx = None
    for i, line in enumerate(lines):
        if line.startswith('##'):
            first_header_idx = i
            break
    cells = []
    # Everything before first header = one cell (all of the authors and affiliations)
    if first_header_idx:
        preamble = '\n'.join(lines[:first_header_idx]).strip()
        if preamble:
            cells.append(preamble)
    # For rest, separate headers into their own cells; for everything else, split by double \n\n via two passes
    current_section = []
    for line in lines[first_header_idx:] if first_header_idx else lines:
        if line.startswith('#'):
            if current_section:
                cells.append('\n'.join(current_section).strip())
                current_section = []
            cells.append(line[1:] if line.startswith('##') else line)
        else:
            current_section.append(line)
    if current_section:
        content = '\n'.join(current_section).strip()
        if content:
            cells.append(content)
    # Split non-header cells by paragraphs
    final_cells = []
    for cell in cells:
        if cell.startswith('#'):
            final_cells.append(cell)
        else:
            paragraphs = cell.split('\n\n')
            final_cells.extend([p.strip() for p in paragraphs if p.strip()])
    
    return final_cells

# %% ../nbs/02-paper2solveit.ipynb #e0d2f51c
import re

async def solve_markdown_paper(markdown_text, citation_patterns=None):
    """Turn a markdown academic paper into appended solveit blocks for incremental reading."""
    
    if citation_patterns is None:
        citation_patterns = [
            r'\([A-Z][^)]*,\s*\d{4}[a-z]?(?:;\s*[^)]*\d{4}[a-z]?)*\)',  # (Author, 2020)
            r'\([A-Z][^)]*\s+\d{4}[a-z]?(?:;\s*[^)]*\d{4}[a-z]?)*\)'    # (Author 2020)
        ]
    
    # Extract references section (only until next ## header)
    refs_match = re.search(r'^## References\s*\n(.*?)(?=^##|\Z)', 
                          markdown_text, re.MULTILINE | re.DOTALL)
    refs_section = refs_match.group(1).strip() if refs_match else ""
    
    # Find all unique citations
    all_citations = {}
    counter = 1
    cells = split_markdown_into_cells(markdown_text)
    
    for cell in cells:
        for pattern in citation_patterns:
            for match in re.finditer(pattern, cell):
                citation = match.group(0)
                if citation not in all_citations:
                    all_citations[citation] = counter
                    counter += 1
    
    # Add full bibliography at start (collapsed)
    if refs_section:
        await add_msg(content=f"### Full References\n\n{refs_section}", 
                placement='at_end', i_collapsed=1)
    
    # Track sections: {header_id: set_of_citations}
    section_citations = {}
    current_header_id = None
    
    for cell in cells:
        if cell.startswith('##'):
            # Add header and remember its ID
            current_header_id = await add_msg(content=cell, placement='at_end')
            section_citations[current_header_id] = set()
        else:
            # Replace citations with footnotes
            modified_cell = cell
            for pattern in citation_patterns:
                for match in re.finditer(pattern, cell):
                    cite_text = match.group(0)
                    if cite_text in all_citations:
                        if current_header_id:
                            section_citations[current_header_id].add(cite_text)
                        modified_cell = modified_cell.replace(
                            cite_text, f"[{all_citations[cite_text]}]", 1
                        )
            
            await add_msg(content=modified_cell, placement='at_end')
    
    # Now go back and insert cheatsheets after each header
    for header_id, citations in section_citations.items():
        if citations:
            cheatsheet = "### Citations in this section\n\n" + "\n".join(
                f"[{all_citations[c]}]: {c}" 
                for c in sorted(citations, key=lambda x: all_citations[x])
            )
            await add_msg(content=cheatsheet, placement='add_after', 
                    id=header_id, i_collapsed=1)

# %% ../nbs/02-paper2solveit.ipynb #462caa66
async def paper2solveit(url, **kwargs):
    """Download a paper from URL (arXiv or PDF) and process into solveit blocks.
    
    Args:
        url: arXiv abstract URL or direct PDF link
        **kwargs: passed to solve_markdown_paper (e.g., citation_patterns)
    """
    # Download PDF to temp file
    f = download_to_temp(url)
    
    # Convert to markdown
    o = await pdf2md(str(f))
    
    # Process into solveit blocks with citations
    await solve_markdown_paper(o["markdown"], **kwargs)

# %% ../nbs/02-paper2solveit.ipynb #2d97de59
__all__ = [
    'pdf2md', 'pdfs2md',  # Jeremy's Marker API wrappers
    'download_to_temp',
    'split_markdown_into_cells',
    'solve_markdown_paper',
    'paper2solveit'
]
