"""Docs: https://professorwug.github.io/kmacsolves/01-supernote-to-solveit.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01-supernote-to-solveit.ipynb.

# %% auto #0
__all__ = ['SCOPES', 'auth_google_drive', 'fetch_supernote_notebooks', 'recents', 'download_notebook', 'load_notebook',
           'page_to_png', 'page_to_prompt', 'sha256_bytes', 'sha256_text', 'PenmanDB', 'couplenb', 'page_png_hash',
           'find_coupling', 'find_changed_nb_pages', 'penman_prompt_transcription', 'current_cell_text_hash',
           'insertion_point_for_new_page', 'poll_drive_and_update_modified_nbs', 'daemon', 'update_dialog_paths']

# %% ../nbs/01-supernote-to-solveit.ipynb #a54543a8
import asyncio

# %% ../nbs/01-supernote-to-solveit.ipynb #4a9bc711
import os.path
from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

SCOPES = ["https://www.googleapis.com/auth/drive.readonly"]

def auth_google_drive(token_path = '/app/data/.secrets/drive_token.json'):
    creds = None
    if os.path.exists(token_path):
        creds = Credentials.from_authorized_user_file(token_path, SCOPES)
    if not creds or not creds.valid:
        if creds and creds.expired and creds.refresh_token:
            creds.refresh(Request())
        else:
            client_config = {
                "installed": {
                    "client_id": os.environ["GOOGLE_CLIENT_ID"],
                    "client_secret": os.environ["GOOGLE_CLIENT_SECRET"],
                    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                    "token_uri": "https://oauth2.googleapis.com/token",
                    "redirect_uris": ["http://localhost"],
                }
            }
            flow = InstalledAppFlow.from_client_config(client_config, SCOPES)
            creds = flow.run_local_server(port=0, open_browser=False)
        with open(token_path, "w") as token:
            token.write(creds.to_json())
    return build("drive", "v3", credentials=creds)

def _resolve_folder_id(service, path_parts):
    """Walk a list of folder names (e.g ['Supernote', 'Note']) to find the final folder ID."""
    parent = "root"
    for name in path_parts:
        resp = service.files().list(
            q=f"name = '{name}' and '{parent}' in parents and mimeType = 'application/vnd.google-apps.folder'",
            fields="files(id)", pageSize=1
        ).execute()
        files = resp.get("files", [])
        if not files: raise FileNotFoundError(f"Folder '{name}' not found under parent {parent}")
        parent = files[0]["id"]
    return parent

def fetch_supernote_notebooks(service, subfolder=None):
    """List .note files in Supernote/Note/, ordered by most recently modified."""
    folder_id = _resolve_folder_id(service, ["Supernote", "Note", subfolder]) if subfolder else _resolve_folder_id(service, ["Supernote", "Note"])
    results = service.files().list(
        q=f"'{folder_id}' in parents and name contains '.note'",
        fields="files(id, name, modifiedByMeTime)",
        orderBy="modifiedByMeTime desc",
        pageSize=100
    ).execute()
    return results.get("files", [])

# %% ../nbs/01-supernote-to-solveit.ipynb #5181877f
def recents(service=None, n=5, subfolder = None):
    if service is None: service = auth_google_drive()
    notebooks = fetch_supernote_notebooks(service, subfolder=subfolder)
    for i, nb in enumerate(notebooks[:n], 0):
        print(f"{i}. {nb['name']}  (modified {nb['modifiedByMeTime'][:10]})")
    return notebooks[:n]

# %% ../nbs/01-supernote-to-solveit.ipynb #9961a138
def download_notebook(service, file_id, dest_dir="/app/data/tmp/enbs/"):
    meta = service.files().get(fileId=file_id, fields="name").execute()
    path = os.path.join(dest_dir, meta["name"])
    content = service.files().get_media(fileId=file_id).execute()
    with open(path, "wb") as f:
        f.write(content)
    return path

# %% ../nbs/01-supernote-to-solveit.ipynb #4a11c3c5
import supernotelib
def load_notebook(nb_dict):
    "Returns a supernotelib nb object with extra metadata attributes, readable by `page_to_prompt`"
    path = download_notebook(auth_google_drive(),nb_dict['id'])
    with open(path, 'rb') as f:
        nb = supernotelib.load(f)
    # nb metadata used downstream
    nb.drive_id = nb_dict["id"]
    nb.drive_name = nb_dict["name"]
    nb.drive_modified_time = nb_dict.get("modifiedByMeTime")
    return nb

# %% ../nbs/01-supernote-to-solveit.ipynb #4ee573ce
from supernotelib.converter import ImageConverter
def page_to_png(nb, page_idx):
    c = ImageConverter(nb)
    if page_idx < 0: page_idx = len(nb.pages) + page_idx
    ci = c.convert(page_number=page_idx)
    return ci


# %% ../nbs/01-supernote-to-solveit.ipynb #1e0c6fd3
from pathlib import Path
import json, os, re, time
from google import genai
from supernotelib.converter import ImageConverter
from dialoghelper.solveitskill import add_msg, update_msg

# %% ../nbs/01-supernote-to-solveit.ipynb #e9e8818e
async def page_to_prompt(
    nb,
    page_idx=-1, # defaults to last page
    notebook_key=None, # identifier used when saving the nb to the filesystem. If blank, defaults to .drive_id attribute added by `load_notebook`.
    model="gemini-3.5-flash", # gemini model identifier for transcription
    insert_placement = 'at_end', # or 'add_after', 'add_before'
    insert_id = '', # id of cell to insert after; uses current message if blank
    dialog_name = '', # dialog to insert prompt cell in
    run=True, # execute the prompt cell after creation
    wait=False, 
):
    """ Inserts the specified page of the supernote nb as a prompt cell, including both the image (visible to SolveIt's LLM) and a gemini transcription (that can be edited by the human). 
    First downloads the specified page as a png to `app/data/penman/pages/notebook_key/page_id`.
    TODO: prompt cell currently inserted at the end of the dialog. Make this customizable.
    """
    page_number = page_idx if page_idx >= 0 else len(nb.pages)+page_idx
    page = nb.get_page(page_number)
    page_id = page.metadata.get("PAGEID", f"page_{page_number}")
    if notebook_key is None: notebook_key = nb.drive_id
    safe_key = re.sub(r"[^a-zA-Z0-9_.-]+", "_", notebook_key).strip("_")

    img_dir = Path("/app/data/penman/pages") / safe_key
    img_dir.mkdir(parents=True, exist_ok=True)

    img_path = img_dir / f"{page_number:04d}_{page_id}_{time.time_ns()}.png"
    img = ImageConverter(nb).convert(page_number=page_number)
    img.save(img_path)

    client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])
    response = client.models.generate_content(
        model=model,
        contents=[
            "Transcribe this handwritten page. Output only the transcribed text, preserving essential structure "
            "(headings, lists via `-`, paragraphs, italics) but abstracting away notebook-specific layout details. "
            "When the page has equations, transcribe them into latex with `$` and `$$` delimiters. "
            "When the page has diagrams suitably amenable, render them as mermaid diagrams or TikZ.",
            img,
        ],
    )

    png_hash = sha256_bytes(img_path.read_bytes())
    transcription = response.text.strip()
    static_path = "/" + str(img_path.relative_to("/app/data"))
    static_url = f"/static{static_path}#ai"

    meta = {
        "kind": "penman-supernote-page",
        "notebook_key": notebook_key,
        "page_number": page_number,
        "page_id": page_id,
        "image_path": str(img_path),
        "page_png_hash": png_hash,
        "static_url": static_url,
    }

    content = f"""<!-- penman:{json.dumps(meta, sort_keys=True)} -->

![Supernote page {page_number + 1}]({static_url})

{transcription}
"""
    if insert_placement == 'replace':
        if not insert_id: raise ValueError("insert_id required for insert_placement='replace'")
        await update_msg(id=insert_id, content=content, msg_type="prompt", dname=dialog_name or '')
        msg_id = insert_id
    else:
        msg_id = await add_msg(content, msg_type="prompt", run=run, wait=wait, placement = insert_placement, id=insert_id, dname=dialog_name or "")
    return {
        "msg_id": msg_id,
        "page_id": page_id,
        "image_path": str(img_path),
        "static_url": static_url,
        "transcription": transcription,
        "page_png_hash": png_hash,
        "cell_contents":content,
    }

# %% ../nbs/01-supernote-to-solveit.ipynb #e91973bd
import sqlite3, hashlib, time
from pathlib import Path

def sha256_bytes(bs: bytes) -> str:
    return hashlib.sha256(bs).hexdigest()

def sha256_text(s: str) -> str:
    return hashlib.sha256(s.encode("utf-8")).hexdigest()

class PenmanDB:
    def __init__(self, path="/app/data/penman/penman.sqlite"):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.conn = sqlite3.connect(self.path)
        self.conn.row_factory = sqlite3.Row
        self.ensure_schema()

    def ensure_schema(self):
        self.conn.executescript("""
        PRAGMA foreign_keys = ON;

        CREATE TABLE IF NOT EXISTS couplings (
            id INTEGER PRIMARY KEY,
            drive_id TEXT NOT NULL UNIQUE,
            drive_name TEXT NOT NULL,
            dialog_name TEXT NOT NULL,
            drive_modified_time TEXT,
            created_at REAL NOT NULL,
            updated_at REAL NOT NULL,
            locked_at REAL,
            locked_by TEXT
        );

        CREATE TABLE IF NOT EXISTS pages (
            id INTEGER PRIMARY KEY,
            coupling_id INTEGER NOT NULL REFERENCES couplings(id) ON DELETE CASCADE,
            page_id TEXT NOT NULL,
            page_index INTEGER NOT NULL,
            cell_id TEXT NOT NULL,
            image_path TEXT NOT NULL,
            page_png_hash TEXT NOT NULL,
            cell_text_hash TEXT NOT NULL,
            created_at REAL NOT NULL,
            updated_at REAL NOT NULL,
            UNIQUE(coupling_id, page_id)
        );
        """)
        self.conn.commit()

    def couple(self, *, drive_id, drive_name, dialog_name, drive_modified_time=None):
        now = time.time()
        self.conn.execute("""
        INSERT INTO couplings
            (drive_id, drive_name, dialog_name, drive_modified_time, created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, ?)
        ON CONFLICT(drive_id) DO UPDATE SET
            drive_name=excluded.drive_name,
            dialog_name=excluded.dialog_name,
            drive_modified_time=excluded.drive_modified_time,
            updated_at=excluded.updated_at
        """, (drive_id, drive_name, dialog_name, drive_modified_time, now, now))
        self.conn.commit()
        return self.get_coupling(drive_id=drive_id)

    def get_coupling(self, *, drive_id=None, id=None):
        if drive_id is not None:
            row = self.conn.execute("SELECT * FROM couplings WHERE drive_id=?", (drive_id,)).fetchone()
        else:
            row = self.conn.execute("SELECT * FROM couplings WHERE id=?", (id,)).fetchone()
        return dict(row) if row else None

    def list_couplings(self):
        rows = self.conn.execute("SELECT * FROM couplings ORDER BY updated_at DESC").fetchall()
        return [dict(r) for r in rows]

    def upsert_page(
        self, *,
        coupling_id,
        page_id,
        page_index,
        cell_id,
        image_path,
        page_png_hash,
        cell_text_hash,
    ):
        now = time.time()
        self.conn.execute("""
        INSERT INTO pages
            (coupling_id, page_id, page_index, cell_id, image_path,
             page_png_hash, cell_text_hash, created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
        ON CONFLICT(coupling_id, page_id) DO UPDATE SET
            page_index=excluded.page_index,
            cell_id=excluded.cell_id,
            image_path=excluded.image_path,
            page_png_hash=excluded.page_png_hash,
            cell_text_hash=excluded.cell_text_hash,
            updated_at=excluded.updated_at
        """, (
            coupling_id, page_id, page_index, cell_id, image_path,
            page_png_hash, cell_text_hash, now, now,
        ))
        self.conn.commit()
        return self.get_page(coupling_id=coupling_id, page_id=page_id)

    def get_page(self, *, coupling_id, page_id):
        row = self.conn.execute("""
        SELECT * FROM pages
        WHERE coupling_id=? AND page_id=?
        """, (coupling_id, page_id)).fetchone()
        return dict(row) if row else None

    def list_pages(self, *, coupling_id):
        rows = self.conn.execute("""
        SELECT * FROM pages
        WHERE coupling_id=?
        ORDER BY page_index
        """, (coupling_id,)).fetchall()
        return [dict(r) for r in rows]

    def delete_page(self, *, coupling_id, page_id):
        self.conn.execute("""
        DELETE FROM pages
        WHERE coupling_id=? AND page_id=?
        """, (coupling_id, page_id))
        self.conn.commit()
    def delete_coupling(self, *, id):
        self.conn.execute("DELETE FROM couplings WHERE id=?", (id,))
        self.conn.commit()
        
    def acquire_coupling_lock(self, *, coupling_id, locked_by="manual", stale_after=300):
        """Acquire lock for coupling_id. Returns True if acquired, False if already locked."""
        now = time.time()
        stale_before = now - stale_after
        cur = self.conn.execute("""
            UPDATE couplings
            SET locked_at=?, locked_by=?
            WHERE id=?
            AND (locked_at IS NULL OR locked_at < ?)
        """, (now, locked_by, coupling_id, stale_before))
        self.conn.commit()
        return cur.rowcount == 1

    def release_coupling_lock(self, *, coupling_id, locked_by=None):
        """Release lock. If locked_by is provided, only release matching locks."""
        if locked_by is None:
            self.conn.execute("""
                UPDATE couplings
                SET locked_at=NULL, locked_by=NULL
                WHERE id=?
            """, (coupling_id,))
        else:
            self.conn.execute("""
                UPDATE couplings
                SET locked_at=NULL, locked_by=NULL
                WHERE id=? AND locked_by=?
            """, (coupling_id, locked_by))
        self.conn.commit()


# %% ../nbs/01-supernote-to-solveit.ipynb #bd57335b
from dialoghelper.solveitskill import curr_dialog

async def couplenb(
    nb_dict, # from .recents()
    dialog_name=None, # defaults to current dialog
    db=None, # defaults to PenmanDB in /app/data/penman/penman.sqlite
    run=False # run all inserted prompts?
    ):
    """Couple a Supernote Drive notebook to a Solveit dialog and import pages once."""
    if db is None:
        db = PenmanDB()
    if dialog_name is None:
        d = await curr_dialog()
        dialog_name = "/" + (d["name"] if isinstance(d, dict) else d)
    elif not dialog_name.startswith("/"):
        d = await curr_dialog()
        curr_name = d["name"] if isinstance(d, dict) else d
        dialog_name = "/" + str(Path(curr_name).parent / dialog_name)

    nb = load_notebook(nb_dict)

    coupling = db.couple(
        drive_id=nb.drive_id,
        drive_name=nb.drive_name,
        dialog_name=dialog_name,
        drive_modified_time=nb.drive_modified_time,
    )

    existing_pages = db.list_pages(coupling_id=coupling["id"])
    if existing_pages:
        print(f"Already coupled: {len(existing_pages)} pages recorded.")
        return coupling

    for page_idx in range(len(nb.pages)):
        res = await page_to_prompt(
            nb,
            page_idx=page_idx,
            notebook_key=nb.drive_id,
            insert_placement = 'at_end',
            run=run,
            wait=False,
            dialog_name=dialog_name,
        )
        page_png_hash = sha256_bytes(Path(res["image_path"]).read_bytes())
        cell_text_hash = sha256_text(res["cell_contents"].strip())

        db.upsert_page(
            coupling_id=coupling["id"],
            page_id=res["page_id"],
            page_index=page_idx,
            cell_id=res["msg_id"],
            image_path=res["image_path"],
            page_png_hash=page_png_hash,
            cell_text_hash=cell_text_hash,
        )

    return coupling

# %% ../nbs/01-supernote-to-solveit.ipynb #d6807288
from io import BytesIO
from supernotelib.converter import ImageConverter

def page_png_hash(nb, page_idx):
    img = ImageConverter(nb).convert(page_number=page_idx)
    bio = BytesIO()
    img.save(bio, format="PNG")
    return sha256_bytes(bio.getvalue())

def find_coupling(db, drive_id=None, drive_name=None, dialog_name=None):
    matches = db.list_couplings()
    if drive_id is not None:
        matches = [c for c in matches if c["drive_id"] == drive_id]
    if drive_name is not None:
        matches = [c for c in matches if c["drive_name"] == drive_name]
    if dialog_name is not None:
        matches = [c for c in matches if c["dialog_name"] == dialog_name]
    if not matches:
        raise KeyError("No matching coupling found")
    if len(matches) > 1:
        raise ValueError(f"Ambiguous coupling lookup: {len(matches)} matches")
    return matches[0]

# %% ../nbs/01-supernote-to-solveit.ipynb #e9b2384f
async def find_changed_nb_pages(drive_id=None, drive_name=None, dialog_name=None, db=None):
    """Load a nb-dialog coupling given some identifying information, and return a dict with 
    new_pages, changed_pages, removed_pages, reordered_pages"""
    if db is None:
        db = PenmanDB()

    coupling = find_coupling(
        db,
        drive_id=drive_id,
        drive_name=drive_name,
        dialog_name=dialog_name,
    )

    service = auth_google_drive()
    nb_meta = service.files().get(
        fileId=coupling["drive_id"],
        fields="id, name, modifiedByMeTime",
    ).execute()
    nb = load_notebook(nb_meta)

    old_pages = {
        row["page_id"]: row
        for row in db.list_pages(coupling_id=coupling["id"])
    }

    current_pages = []
    new_pages = []
    changed_pages = []
    reordered_pages = []

    for page_idx in range(len(nb.pages)):
        page = nb.get_page(page_idx)
        page_id = page.metadata.get("PAGEID", f"page_{page_idx}")
        png_hash = page_png_hash(nb, page_idx)

        current = {
            "page_idx": page_idx,
            "page_id": page_id,
            "page_png_hash": png_hash,
        }
        current_pages.append(current)

        old = old_pages.get(page_id)
        if old is None:
            new_pages.append(current)
        elif old["page_png_hash"] != png_hash:
            changed_pages.append({
                **current,
                "old": old,
            })
        elif old["page_index"] != page_idx:
            reordered_pages.append({**current, "old": old})

    current_page_ids = {p["page_id"] for p in current_pages}
    removed_pages = [
        row for page_id, row in old_pages.items()
        if page_id not in current_page_ids
    ]

    return {
        "coupling": coupling,
        "notebook": nb,
        "notebook_meta": nb_meta,
        "current_pages": current_pages,
        "new_pages": new_pages,
        "changed_pages": changed_pages,
        "removed_pages": removed_pages,
        "reordered_pages": reordered_pages,
    }

# %% ../nbs/01-supernote-to-solveit.ipynb #9021645f
from dialoghelper.solveitskill import read_msgid, del_msgs

def penman_prompt_transcription(content):
    """Extract transcription from a generated penman prompt cell."""
    parts = content.split("\n\n", 2)
    return parts[2].strip() if len(parts) >= 3 else content.strip()

async def current_cell_text_hash(cell_id, dialog_name=""):
    """Hash the full current prompt cell content for manual-edit detection."""
    msg = await read_msgid(cell_id, dname=dialog_name)
    content = msg.get("content") or msg.get("source") or ""
    return sha256_text(content.strip())

# %% ../nbs/01-supernote-to-solveit.ipynb #e92c89a4
def insertion_point_for_new_page(page_idx, current_pages, old_pages):
    """Return placement/id for inserting a new page in current Supernote order."""
    for p in current_pages:
        if p["page_idx"] > page_idx and p["page_id"] in old_pages:
            return "add_before", old_pages[p["page_id"]]["cell_id"]
    return "at_end", ""

# %% ../nbs/01-supernote-to-solveit.ipynb #281d38fd
async def poll_drive_and_update_modified_nbs(
    db=None,
    service=None,
    run_new=False,
    origin_process="penman-daemon",
):
    """Poll coupled Google Drive notebooks and update any whose modified time changed."""
    if db is None:
        db = PenmanDB()
    if service is None:
        service = auth_google_drive()

    results = {
        "checked": [],
        "updated": [],
        "unchanged": [],
        "errors": [],
    }

    for coupling in db.list_couplings():
        drive_id = coupling["drive_id"]

        try:
            meta = service.files().get(
                fileId=drive_id,
                fields="id, name, modifiedByMeTime",
            ).execute()

            old_mtime = coupling.get("drive_modified_time")
            new_mtime = meta.get("modifiedByMeTime")

            record = {
                "coupling": coupling,
                "drive_meta": meta,
            }
            results["checked"].append(record)

            if old_mtime is not None and new_mtime <= old_mtime:
                results["unchanged"].append(record)
                continue

            sync_res = await updatenb(
                drive_id=drive_id,
                db=db,
                run_new=run_new,
                origin_process=origin_process,
            )
            results["updated"].append(sync_res)
            # print({k: len(v) for k,v in sync_res["results"].items()}, flush=True)

        except Exception as e:
            results["errors"].append({
                "coupling": coupling,
                "error": repr(e),
            })

    return results

# %% ../nbs/01-supernote-to-solveit.ipynb #2edc10af
async def daemon(interval=60, db=None, service=None, run_new=False):
    """Continuously poll Drive and sync modified coupled Supernote notebooks."""
    if db is None:
        db = PenmanDB()
    if service is None:
        service = auth_google_drive()

    while True:
        started = time.time()
        res = await poll_drive_and_update_modified_nbs(
            db=db,
            service=service,
            run_new=run_new,
            origin_process="penman-daemon",
        )
        print({
            "time": time.strftime("%Y-%m-%d %H:%M:%S"),
            "checked": len(res["checked"]),
            "updated": len(res["updated"]),
            "unchanged": len(res["unchanged"]),
            "errors": len(res["errors"]),
        })
        print(json.dumps(res["updated"], default=str, indent=2)[:4000], flush=True)
        if res["errors"]:
            print(res["errors"])
        await asyncio.sleep(max(0, interval - (time.time() - started)))

# %% ../nbs/01-supernote-to-solveit.ipynb #fe52f52c
from difflib import SequenceMatcher
from pathlib import Path
import sqlite3

def _norm_dname(s):
    """Normalize a Solveit dialog name to /path/without/ipynb."""
    if not s: return s
    s = str(s).removesuffix(".ipynb")
    return s if s.startswith("/") else "/" + s

def _dialog_candidates(root="/app/data"):
    """Return absolute Solveit dnames for every ipynb under root."""
    root = Path(root)
    res = []
    for p in root.rglob("*.ipynb"):
        if ".ipynb_checkpoints" in p.parts: continue
        rel = p.relative_to(root).with_suffix("")
        res.append("/" + rel.as_posix())
    return sorted(res)

def _best_dialog_match(old, candidates):
    """Find closest candidate dname to an old stored dname."""
    old = _norm_dname(old)
    if old in candidates:
        return old, 1.0

    old_base = Path(old).name
    best = None
    best_score = -1

    for cand in candidates:
        cand_base = Path(cand).name

        # Prefer basename similarity, but include full path as a tiebreaker.
        base_score = SequenceMatcher(None, old_base, cand_base).ratio()
        full_score = SequenceMatcher(None, old, cand).ratio()
        score = 0.75 * base_score + 0.25 * full_score

        if score > best_score:
            best = cand
            best_score = score

    return best, best_score

# %% ../nbs/01-supernote-to-solveit.ipynb #85fd7c4d
def update_dialog_paths(
    db_path="/app/data/penman/penman.sqlite",
    root="/app/data",
    dry_run=True,
    cutoff=0.55,
):
    """Update coupling dialog_name values to closest existing Solveit dialog paths.

    Returns a list of proposed/applied changes.
    """
    candidates = _dialog_candidates(root)
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row

    rows = [dict(r) for r in conn.execute(
        "SELECT id, drive_id, drive_name, dialog_name FROM couplings"
    ).fetchall()]

    changes = []
    for row in rows:
        old = _norm_dname(row["dialog_name"])
        new, score = _best_dialog_match(old, candidates)

        rec = {
            **row,
            "old_dialog_name": row["dialog_name"],
            "new_dialog_name": new,
            "score": score,
            "changed": new != row["dialog_name"] and score >= cutoff,

        }
        changes.append(rec)

        if rec["changed"] and not dry_run:
            conn.execute(
                "UPDATE couplings SET dialog_name=? WHERE id=?",
                (new, row["id"]),
            )

    if not dry_run:
        conn.commit()
    conn.close()
    return changes
